services:
  quasselstrippe-server:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./server/data:/usr/src/server/data
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
    restart: unless-stopped